name: ct484_project
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  page_transition: ^2.0.0
  intl: ^0.19.0
  provider: ^6.0.5
  flutter_dotenv: ^5.1.0
  http: ^1.1.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/products/product_1.png
    - assets/images/products/
    - assets/images/banners/
    - assets/images/logos/
    - assets/images/backgrounds/
    - .env
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
    - family: RobotoSerif
      fonts:
        - asset: assets/fonts/RobotoSerif-Regular.ttf
